name: NachbarschaftsPlugin1992
version: 1.0.0
main: de.nachbarschaft.Main
api-version: 1.21
authors: [ "DU" ]

commands:
  kapitel:
    description: Steuert die Story Kapitel
  ritual:
    description: Führt gefährliche Rituale im Nether aus
  sanctum:
    description: Öffnet Zugang zum Sanctum
  adminpalast:
    description: Teleportiert zum Admin Palast
