name: NachbarschaftsPlugin1992
main: de.nachbarschaft.Main
version: 1.0.0
api-version: 1.21
commands:
  adminform:
    description: Starte Admin Transformation
  waffe:
    description: Gibt dir deine Seelenwaffe
  seelenstart:
    description: Beginn der Seelenwaffen-Reise
  adminstory:
    description: Admin Story Infos
  stadtcheck:
    description: Checkt Ober/Unterstadt Status
  sanctumwarn:
    description: Warnung vor dem Sanctum
  ritual:
    description: Ritual Hinweise
 prüfung:     
    description: Startet Prüfung
 sanctum:     
    description: Teleport ins Sanctum

