name: NachbarschaftsPlugin1992
version: 1.0.0
main: de.nachbarschaft.Main
api-version: 1.21
commands:
  kapitelstart:
    description: Startet die Hauptstory und teleportiert dich in die Oberstadt
  stadtcheck:
    description: Zeigt Ober- und Unterstadt-Koordinaten

