name: Nachbarschaft
version: 1.0
main: de.nachbarschaft.Main
api-version: 1.21

commands:
  sanctum:
    description: Teleport ins Sanctum
  sanctumwarn:
    description: Sanctum Warnung
  stadtcheck:
    description: Zeigt Stadtinfos
  adminpalast:
    description: Teleport Admin Palast
  adminform:
    description: Admin Kraft aktivieren
  seelenstart:
    description: Startet Seelenpfad
  waffe:
    description: Gibt Seelenwaffe
  prüfung:
    description: Startet Prüfung
  kapitel:
    description: Story Kapitel
  adminstory:
    description: Startet Admin Story
  adminhelp:
    description: Hilfe
  voicecmd:
    description: Voice-Befehl auslösen
  regel:
    description: Regeln verwalten
  rules:
    description: Regeln verwalten
