name: NachbarschaftsPlugin1992
main: de.nachbarschaft.Main
version: 1.0
api-version: 1.21
commands:
  sanctum: {}
  sanctumwarn: {}
  stadtcheck: {}
  adminpalast: {}
  adminform: {}
  seelenstart: {}
  waffe: {}
  prüfung: {}
  kapitel: {}
  adminstory: {}
  adminhelp: {}
