name: NachbarschaftsPlugin1992
version: 1.0.0
main: de.nachbarschaft.Main
api-version: 1.21

commands:
  kapitelstart:
    description: Startet Phase 3 Story
  stadtcheck:
    description: Zeigt St채dte
  sanctum:
    description: Teleportiert ins Sanctum der Admins
  adminhilfe:
    description: Ruft Admin Unterst체tzung
  adminstory:
    description: Startet Phase 4 Story
  adminform:
    description: Startet Admin Verwandlung
  seelenstart:
    description: Aktiviert Seelenwaffen System
  waffe:
    description: Gibt Seelenwaffe
  pr체fung:
    description: Startet eine Admin Pr체fung
  sanctumwarn:
    description: Warnevent im Sanctum
  adminfinal:
    description: Startet Finalstory Phase

