name: NachbarschaftsPlugin1992
main: de.nachbarschaft.Main
version: 1.0.0
api-version: 1.21
commands:
  adminform:
    description: Admin Transformation
  sanctum:
    description: Teleport ins Sanctum
  sanctumwarn:
    description: Warnung des Sanctums
  ritual:
    description: Startet Ritual System
  seelenstart:
    description: Startet Seelen System
  waffe:
    description: Gibt die Seelenwaffe
  prüfung:
    description: Startet Prüfung
  adminstory:
    description: Startet Admin Story
  stadtcheck:
    description: Status Ober & Unterstadt


