name: NachbarschaftsPlugin1992
version: 1.0.0
main: de.nachbarschaft.Main
api-version: 1.21
author: Yami
description: Minecraft Nachbarschaft – Admins, Commandblöcke, Story

commands:
  adminhilfe:
    description: Ruft einen Admin
  storystart:
    description: Startet die Story manuell
  commandblock:
    description: Gibt einen Commandblock

permissions:
  nachbarschaft.admin:
    default: op
